# Generated by Django 2.0.7 on 2018-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gooderreads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/en/1/18/Lonesome_Dove.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
