# Generated by Django 2.0.7 on 2018-07-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gooderreads', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Ravi', max_length=32),
            preserve_default=False,
        ),
    ]
