# Generated by Django 2.0.7 on 2018-08-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gooderreads', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isbn',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
